"""create_awards_and_recreate_slides

Revision ID: 04770d69f3b0
Revises: b7a95e08840e
Create Date: 2026-07-07 15:59:58.035883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04770d69f3b0'
down_revision: Union[str, None] = 'b7a95e08840e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM hero_slides")
    op.create_table('recognitions_and_awards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_media_id', sa.Uuid(), nullable=False),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_media_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hero_slides', sa.Column('subtitle', sa.String(length=255), nullable=True))
    op.add_column('hero_slides', sa.Column('image_media_id', sa.Uuid(), nullable=False))
    op.add_column('hero_slides', sa.Column('order_position', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hero_slides', 'images', ['image_media_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hero_slides', 'image_url')
    op.drop_column('hero_slides', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero_slides', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hero_slides', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hero_slides', type_='foreignkey')
    op.drop_column('hero_slides', 'order_position')
    op.drop_column('hero_slides', 'image_media_id')
    op.drop_column('hero_slides', 'subtitle')
    op.drop_table('recognitions_and_awards')
    # ### end Alembic commands ###
