"""rename_portfolio_galleries_and_add_slots

Revision ID: 356c92857feb
Revises: 04770d69f3b0
Create Date: 2026-07-07 22:44:03.353970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '356c92857feb'
down_revision: Union[str, None] = '04770d69f3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_busy_time',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_full_day', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_busy_time_date'), 'admin_busy_time', ['date'], unique=False)
    
    op.create_table('booking_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('booking_request_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'start_time', 'end_time', name='uq_booking_slot_time')
    )
    op.create_index(op.f('ix_booking_slots_date'), 'booking_slots', ['date'], unique=False)
    
    # Rename galleries table and update columns
    op.rename_table('galleries', 'portfolio_galleries')
    op.alter_column('portfolio_galleries', 'title', new_column_name='name')
    op.alter_column('portfolio_galleries', 'cover_image_id', new_column_name='cover_media_id')
    op.alter_column('portfolio_galleries', 'sort_order', new_column_name='order_position')
    
    op.add_column('portfolio_galleries', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.execute("UPDATE portfolio_galleries SET is_active = (status = 'published')")
    
    op.drop_column('portfolio_galleries', 'status')
    op.drop_column('portfolio_galleries', 'category')
    
    op.execute("DROP INDEX IF EXISTS ix_galleries_category")
    op.execute("DROP INDEX IF EXISTS ix_galleries_slug")
    op.create_index(op.f('ix_portfolio_galleries_slug'), 'portfolio_galleries', ['slug'], unique=True)
    
    op.add_column('bookings', sa.Column('session_type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_bookings_session_type'), 'bookings', ['session_type'], unique=False)
    
    # Update gallery_images
    op.drop_constraint('uq_gallery_image', 'gallery_images', type_='unique')
    op.drop_constraint('gallery_images_gallery_id_fkey', 'gallery_images', type_='foreignkey')
    op.drop_constraint('gallery_images_image_id_fkey', 'gallery_images', type_='foreignkey')
    op.drop_index('ix_gallery_images_image_id', table_name='gallery_images')
    
    op.alter_column('gallery_images', 'image_id', new_column_name='image_media_id')
    op.alter_column('gallery_images', 'sort_order', new_column_name='order_position')
    op.execute("UPDATE gallery_images SET order_position = 0 WHERE order_position IS NULL")
    op.alter_column('gallery_images', 'order_position', nullable=False, server_default='0')
    
    op.create_unique_constraint('uq_gallery_image', 'gallery_images', ['gallery_id', 'image_media_id'])
    op.create_index(op.f('ix_gallery_images_image_media_id'), 'gallery_images', ['image_media_id'], unique=False)
    
    op.create_foreign_key(None, 'gallery_images', 'images', ['image_media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gallery_images', 'portfolio_galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('images_gallery_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'portfolio_galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_gallery_id_fkey', 'images', 'portfolio_galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint(None, 'gallery_images', type_='foreignkey')
    op.drop_constraint(None, 'gallery_images', type_='foreignkey')
    op.drop_index(op.f('ix_gallery_images_image_media_id'), table_name='gallery_images')
    op.drop_constraint('uq_gallery_image', 'gallery_images', type_='unique')
    
    op.alter_column('gallery_images', 'image_media_id', new_column_name='image_id')
    op.alter_column('gallery_images', 'order_position', new_column_name='sort_order', nullable=True)
    
    op.create_unique_constraint('uq_gallery_image', 'gallery_images', ['gallery_id', 'image_id'])
    op.create_index('ix_gallery_images_image_id', 'gallery_images', ['image_id'], unique=False)
    
    op.create_foreign_key('gallery_images_image_id_fkey', 'gallery_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('gallery_images_gallery_id_fkey', 'gallery_images', 'portfolio_galleries', ['gallery_id'], ['id'], ondelete='CASCADE')
    
    op.drop_index(op.f('ix_bookings_session_type'), table_name='bookings')
    op.drop_column('bookings', 'session_type')
    
    op.rename_table('portfolio_galleries', 'galleries')
    op.alter_column('galleries', 'name', new_column_name='title')
    op.alter_column('galleries', 'cover_media_id', new_column_name='cover_image_id')
    op.alter_column('galleries', 'order_position', new_column_name='sort_order', nullable=True)
    
    op.add_column('galleries', sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'))
    op.add_column('galleries', sa.Column('category', sa.String(length=100), nullable=False, server_default='newborn'))
    
    op.execute("UPDATE galleries SET status = CASE WHEN is_active THEN 'published' ELSE 'draft' END")
    op.drop_column('galleries', 'is_active')
    
    op.drop_index('ix_portfolio_galleries_slug', table_name='galleries')
    op.create_index('ix_galleries_slug', 'galleries', ['slug'], unique=True)
    op.create_index('ix_galleries_category', 'galleries', ['category'], unique=False)
    
    op.drop_index(op.f('ix_booking_slots_date'), table_name='booking_slots')
    op.drop_table('booking_slots')
    op.drop_index(op.f('ix_admin_busy_time_date'), table_name='admin_busy_time')
    op.drop_table('admin_busy_time')
    # ### end Alembic commands ###
