"""create_blogs_table

Revision ID: b7a95e08840e
Revises: f8b69f298d72
Create Date: 2026-07-07 09:00:54.496931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7a95e08840e'
down_revision: Union[str, None] = 'f8b69f298d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_media_id', sa.Uuid(), nullable=True),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('body_content', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thumbnail_media_id'], ['images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.drop_index('ix_blog_posts_category', table_name='blog_posts')
    op.drop_index('ix_blog_posts_slug', table_name='blog_posts')
    op.drop_table('blog_post_translations')
    op.drop_table('blog_posts')
    op.drop_constraint('fk_client_gallery_images_media', 'client_gallery_images', type_='foreignkey')
    op.drop_column('client_gallery_images', 'cached_image_url')
    op.drop_column('client_gallery_images', 'cached_filename')
    op.drop_column('client_gallery_images', 'media_id')
    op.drop_index('ix_media_category', table_name='media')
    op.drop_index('ix_media_file_url', table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_gallery_images', sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('client_gallery_images', sa.Column('cached_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('client_gallery_images', sa.Column('cached_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_client_gallery_images_media', 'client_gallery_images', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_table('media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name='media_uploaded_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_pkey'),
    sa.UniqueConstraint('file_url', name='media_file_url_key')
    )
    op.create_index('ix_media_file_url', 'media', ['file_url'], unique=True)
    op.create_index('ix_media_category', 'media', ['category'], unique=False)
    op.create_table('blog_post_translations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blog_post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], name='blog_post_translations_blog_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='blog_post_translations_pkey'),
    sa.UniqueConstraint('blog_post_id', 'language', name='uq_blog_post_language')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cover_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('reading_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blog_posts_pkey')
    )
    op.create_index('ix_blog_posts_slug', 'blog_posts', ['slug'], unique=True)
    op.create_index('ix_blog_posts_category', 'blog_posts', ['category'], unique=False)
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
