"""create galleries and images tables

Revision ID: 034263607a4f
Revises: 14d2b917c89b
Create Date: 2026-06-30 06:58:47.856701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034263607a4f'
down_revision: Union[str, None] = '14d2b917c89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], name='fk_gallery_cover_image', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_category'), 'galleries', ['category'], unique=False)
    op.create_index(op.f('ix_galleries_slug'), 'galleries', ['slug'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('optimized_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_index(op.f('ix_galleries_slug'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_category'), table_name='galleries')
    op.drop_table('galleries')
    # ### end Alembic commands ###
