"""create client galleries tables

Revision ID: 5bfd140d7d67
Revises: 034263607a4f
Create Date: 2026-06-30 08:01:02.315425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfd140d7d67'
down_revision: Union[str, None] = '034263607a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_galleries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('can_replace', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_download_zip', sa.Boolean(), nullable=False),
    sa.Column('can_edit_details', sa.Boolean(), nullable=False),
    sa.Column('can_submit_selections', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('selections_submitted', sa.Boolean(), nullable=False),
    sa.Column('selections_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['images.id'], name='fk_client_gallery_cover_image', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_galleries_slug'), 'client_galleries', ['slug'], unique=True)
    op.create_index(op.f('ix_client_galleries_user_id'), 'client_galleries', ['user_id'], unique=False)
    op.create_table('client_gallery_images',
    sa.Column('client_gallery_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_gallery_id'], ['client_galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_gallery_id', 'image_id')
    )
    op.create_foreign_key('fk_gallery_cover_image', 'galleries', 'images', ['cover_image_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_gallery_cover_image', 'galleries', type_='foreignkey')
    op.drop_table('client_gallery_images')
    op.drop_index(op.f('ix_client_galleries_user_id'), table_name='client_galleries')
    op.drop_index(op.f('ix_client_galleries_slug'), table_name='client_galleries')
    op.drop_table('client_galleries')
    # ### end Alembic commands ###
