"""add_download_zip_url_to_client_galleries

Revision ID: f8b69f298d72
Revises: 1fac1297129c
Create Date: 2026-07-06 23:20:07.381678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8b69f298d72'
down_revision: Union[str, None] = '1fac1297129c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_galleries', sa.Column('download_zip_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_galleries', 'download_zip_url')
    # ### end Alembic commands ###
